#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASS';
  CREATE DATABASE $APP_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_DB_USER;
  \connect $APP_DB_NAME $APP_DB_USER
  
  BEGIN;
    CREATE TABLE IF NOT EXISTS static_data (
	  id BIGINT PRIMARY KEY,
	  data VARCHAR(255) NOT NULL,
	  UNIQUE(id, data)
	);
	CREATE INDEX static_data_id_idx ON static_data (id);
  COMMIT;

EOSQL
